### ISSUE TITLE
Please restore NPCInteractEvent

### ISSUE THREAD

**Issue by bublegum1024** [Pyrbu/ZNPCsPlus#101]
When I use ZNPCsPlus with BeautyQuests, I have an Error message, and BQ does not work :(

[BeautyQuests] Failed to register events for class fr.skytasul.quests.integrations.npcs.BQZNPCsPlus because io/github/znetworkw/znpcservers/npc/interaction/NPCInteractEvent does not exist.

Please implement this interface to make better ZNPCs compatibility.

Thanks.

**Comment by Pyrbu** [comment]
There already is an equivalent for NPCInteractEvent in the 2.0.0 API, the author of BeautyQuests will need to update their implementation to support ZNPCsPlus v2.0.0

**Comment by Pyrbu** [comment]
BeautyQuests now supports the v2.0.0 API since [e06b09052d4fee59744622e24148a61baa371ae8](https://github.com/SkytAsul/BeautyQuests/commit/e06b09052d4fee59744622e24148a61baa371ae8) please use their v1.0 dev builds :)
