### ISSUE TITLE
Error occurred while enabling ZNPCsPlus v1.0.4 (Is it up to date?)

### ISSUE THREAD

**Issue by Overwrite987** [Pyrbu/ZNPCsPlus#11]
https://pastebin.com/1q8aAcby
1.16.5. Again. 
:'>

**Comment by Pyrbu** [comment]
How did you get 1.16.5 to run with Java 17?

**Comment by Overwrite987** [comment]
> How did you get 1.16.5 to run with Java 17?

uh...
a lot of plugins request 17 java, for this...
so i used -DPaper.IgnoreJavaVersion=true flag on statup

**Comment by Pyrbu** [comment]
It loads fine for me. Try re-downloading the latest jar, there was a small shading relocation issue which I fixed and switched out the jar but there were 4 downloads before I switched it out so you were probably one of them

**Comment by Overwrite987** [comment]
> It loads fine for me. Try re-downloading the latest jar, there was a small shading relocation issue which I fixed and switched out the jar but there were 4 downloads before I switched it out so you were probably one of them

yes, it solves the problem!
