### ISSUE TITLE
plugin doesn't support work with viaversion if holo npcs disabled

### ISSUE THREAD

**Issue by SL-69** [Pyrbu/ZNPCsPlus#112]
server version - 1.12.2 (latest)
client version - 1.20.1
if i toggled holo npcs off (/znpcs toggle 1 holo) be error in console:  https://logpaste.com/fkzTMKws
viaversion developers say that this is a problem with zncpcsPlus, but not their plugin, that's why I'm here
![2023-11-12_21 30 10](https://github.com/Pyrbu/ZNPCsPlus/assets/137718036/95b81e07-369a-4822-935e-8b399ba432de)

**Comment by D3v1s0m** [comment]
> server version - 1.12.2 (latest) client version - 1.20.1 if i toggled holo npcs off (/znpcs toggle 1 holo) be error in console: https://logpaste.com/fkzTMKws viaversion developers say that this is a problem with zncpcsPlus, but not their plugin, that's why I'm here ![2023-11-12_21 30 10](https://user-images.githubusercontent.com/137718036/282305486-95b81e07-369a-4822-935e-8b399ba432de.png)

Can you please provide the plugin version?
also, please join [discord](https://discord.gg/MAZz6XpPcg)

**Comment by SL-69** [comment]
1.0.8

**Comment by D3v1s0m** [comment]
@ICodeMonster  please update to 2.0.0 and try again.

**Comment by SL-69** [comment]
plugin doesn't work. logs: https://logpaste.com/xZNhWiDV
and api logs - https://logpaste.com/FOHldza6

**Comment by D3v1s0m** [comment]
> plugin doesn't work. logs: https://logpaste.com/xZNhWiDV 

Please ping me on the [discord server](https://discord.com/channels/1099449144948555957/1099450633410576447)
> api logs - https://logpaste.com/FOHldza6

You are not supposed to put the api jar in the plugins folder
