### ISSUE TITLE
[Bug] Bug with /znpc list

### ISSUE THREAD

**Issue by NoltoxGit** [Pyrbu/ZNPCsPlus#115]
Hello,
When we use the command `/znpc list` and we click on the **[TELEPORT]**, it doesn't work. it puts these errors in the chat :
![image](https://github.com/Pyrbu/ZNPCsPlus/assets/75265787/375438bb-b594-4b2c-8595-81005ed9e407)

**Comment by D3v1s0m** [comment]
@NoltoxGit , that is probably because you also have citizens installed and it is using the citizens /npc command. but I will try to make it so that it does not happen
