### ISSUE TITLE
Skin doesn't update on NPC respawn

### ISSUE THREAD

**Issue by NoltoxGit** [Pyrbu/ZNPCsPlus#116]
Hello,
When we try to use the `/znpc skin (name) url (link)` command, it doesn't automatically change the npc skin.
Would it be possible to make this automatically change the NPC skin when we put a link please ? :)

Here's a video summarising my issue :

https://github.com/Pyrbu/ZNPCsPlus/assets/75265787/5b7e1ee8-1a29-4a7e-ab69-7afa2c56ca39

**Comment by Pyrbu** [comment]
I honestly have no idea why this is happening, it was working on previous versions. It might be because of some internal caching in the client or something.

**Comment by Pyrbu** [comment]
This seems to be working now so I'm closing this issue
