### ISSUE TITLE
MiniMessages does not work in certain conditions

### ISSUE THREAD

**Issue by MattyHD0** [Pyrbu/ZNPCsPlus#120]
When using the `/npc holo add` command on my npc the MiniMessages formatting works correctly, but when using the `set` subcommand instead of `add`, it does not work.

in the following image is shown the npc whose hologram line without formatting use `/npc holo set woodcutter_shop 0 <#864C1A><bold>CLICK` and for the line that has the formatting use `/npc holo add woodcutter_shop <#864C1A><bold>CLICK`, as you can see the text is exactly the same, but when using `set` the corresponding formatting is not applied.

![image](https://github.com/Pyrbu/ZNPCsPlus/assets/53882787/eda03224-ee3d-4277-9a47-e12278730e8a)

Server and Plugin version:

[00:29:21 INFO]: This server is running Pufferfish version git-Pufferfish-40 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 8d20921 on HEAD)

[00:29:32 INFO]: ZNPCsPlus version 2.0.0-SNAPSHOT
[00:29:32 INFO]: Authors: Pyr and D3v1s0m

**Comment by vLuckyyy** [comment]
I fixed this in GH-125 :octocat:
