### ISSUE TITLE
1.20.4 theoretically supported, although with a warning?

### ISSUE THREAD

**Issue by ghost** [Pyrbu/ZNPCsPlus#121]
Good morning,

I would like to use ZNPCsPlus with Quests. I am currently using Paper 379 for 1.20.4 with ZNPCsPlus 1.0.8 and Quests 5.0.0-rc3; Every time I start the server, a following warning is sent to the console:

<img width="939" alt="grafik" src="https://github.com/Pyrbu/ZNPCsPlus/assets/76809077/df0a62c5-a7a4-4373-a4c1-a28e514df311">

I've seen a message on the Spigot page, stating that "1.20.4 is already supported". Is it really?

**Comment by borz7zy** [comment]
How did you launch the plugin on 1.20.4????

**Comment by Pyrbu** [comment]
Yes, 1.20.4 is supported is however you need to be using the dev version that you can get from our discord.
