### ISSUE TITLE
Packet encoding of packet ID 57 threw (skippable? false)

### ISSUE THREAD

**Issue by Krasaw4yk** [Pyrbu/ZNPCsPlus#138]
![изображение_2024-04-27_003525774](https://github.com/Pyrbu/ZNPCsPlus/assets/168237750/87e3367f-1c28-42cc-9b2c-e02b57cc2c91)
![image](https://github.com/Pyrbu/ZNPCsPlus/assets/168237750/cd33b683-4c64-49dc-84df-933b0b1405f3)
I couldn't understand for a long time why I couldn't log in to the server after transferring it to hosting, as everything works fine on my local computer. When I started creating NPCs on my hosting, I was instantly kicked from the server. What should I do? And how do I fix this ID 57?

**Comment by Pyrbu** [comment]
It looks like you're still on version 1.0.8, please try version 2.0.0 from the Jenkins channel in our discord.
