### ISSUE TITLE
[1.0.4] Console colors

### ISSUE THREAD

**Issue by Teslicek** [Pyrbu/ZNPCsPlus#14]
![image](https://user-images.githubusercontent.com/87967222/233772115-1e9440e9-e2fa-4d42-bb6d-65faa6cdd7a8.png)
Used panel: pterodactyl (default)
Server Jar: Pufferfish #67

**Comment by Overwrite987** [comment]
> ![image](https://user-images.githubusercontent.com/87967222/233772115-1e9440e9-e2fa-4d42-bb6d-65faa6cdd7a8.png) Used panel: pterodactyl (default) Server Jar: Pufferfish #67

it isnt really plugin issue
set use-rgb-for-named-text-colors: false in paper-global.yml
