### ISSUE TITLE
Bump packet events

### ISSUE THREAD

**Issue by bridgelol** [Pyrbu/ZNPCsPlus#144]
Bump to 2.3.1-SNAPSHOT as it fixes a memory leak: https://github.com/retrooper/packetevents/pull/763

**Comment by Pyrbu** [comment]
We are now on 2.4.0 (aafdf0b3f9ffd2ddd9b10d1a82a3dda9336aa890)

**Comment by LunarsWorldLLC** [comment]
issue still occuring.
