### ISSUE TITLE
Player lost connection: [ZNPCsPlus] > Couldn't inject interaction detector to channel

### ISSUE THREAD

**Issue by Overwrite987** [Pyrbu/ZNPCsPlus#15]
This error pops-up again
https://pastebin.com/iZAD7VKJ

and this happens quite often...

**Comment by Pyrbu** [comment]
Can you send me the following info:
Minecraft Version
Client Version
List of all other plugins

**Comment by Overwrite987** [comment]
> Can you send me the following info: Minecraft Version Client Version List of all other plugins

version -  Current: git-Plazma-"84f3148" (MC: 1.19.4)* (https://github.com/PlazmaMC/Plazma/releases/tag/latest-1.19.4)
Client Version - ANY. This can happen on any client version randomly
Plugins - Bukkit Plugins: (16): BungeeGuard, CommandWhitelist, DeluxeMenus, ItemJoin, LuckPerms, PlaceholderAPI, ProtocolLib _(latest)_, RestartPlugin, SpawnPlugin, TAB, Vault, ViaBackwards _(latest dev build)_, ViaVersion _(latest dev build)_, WorldEdit, WorldGuard, ZNPCsPlus

**Comment by Pyrbu** [comment]
Can you please use this dev build and provide me with the new stack trace whenever the error happens? I have added some more debug messages to help fix the problem [znpcs.zip](https://github.com/Pyrbu/ZNPCsPlus/files/11301772/znpcs.zip)

**Comment by Overwrite987** [comment]
> Can you please use this dev build and provide me with the new stack trace whenever the error happens? I have added some more debug messages to help fix the problem [znpcs.zip](https://github.com/Pyrbu/ZNPCsPlus/files/11301772/znpcs.zip)

let's see what we have here...

**Comment by Overwrite987** [comment]
Full log - https://mclo.gs/udHp2XP

**Comment by Pyrbu** [comment]
Commit 497f551 should've fixed the issue, please try this jar and let me know.
[znpcs.zip](https://github.com/Pyrbu/ZNPCsPlus/files/11302029/znpcs.zip)

**Comment by Overwrite987** [comment]
> Commit [497f551](https://github.com/Pyrbu/ZNPCsPlus/commit/497f551014a0cc70c204f0db14819816863c1349) should've fixed the issue, please try this jar and let me know. [znpcs.zip](https://github.com/Pyrbu/ZNPCsPlus/files/11302029/znpcs.zip)


it looks like the problem is solved
even after installation on the main server, there was not a single kick
