### ISSUE TITLE
Guarding property (is_retracting_spikes) doesn't work

### ISSUE THREAD

**Issue by UserPIG-byte** [Pyrbu/ZNPCsPlus#154]
Hey, not a huge issue. I was just messing around earlier and realized that the property type for guardian as well as elder guarding with is_retracting_spikes set to false doesn't update it in the data file or even work on the NPC itself. 

Using pufferfish 1.21.1 and zNPCsPlus build #222.

**Comment by Pyrbu** [comment]
The property works fine but the guardian needs to be submerged in water because the animation checks that client-side
