### ISSUE TITLE
ConcurrentModificationException from NpcImpl#setHeadRotation

### ISSUE THREAD

**Issue by m4kii420** [Pyrbu/ZNPCsPlus#164]
![image](https://github.com/user-attachments/assets/641668d1-ab5f-4b93-8b57-5dbe2a8e097e)

**Comment by Pyrbu** [comment]
Sorry I missed that this was from a custom build by D3v1s0m

**Comment by PinoOG** [comment]
> Sorry I missed that this was from a custom build by D3v1s0m

I have the same problem, is there a fix? with latest 2.1.0 SNAPSHOT

**Comment by Pyrbu** [comment]
> I have the same problem, is there a fix? with latest 2.1.0 SNAPSHOT

This should be fixed by ca8a1d649950ea5ac03538c3a30b7b9c12cb33a8
