### ISSUE TITLE
/znpcs glow is broken (as always...)

### ISSUE THREAD

**Issue by Overwrite987** [Pyrbu/ZNPCsPlus#17]
https://pastebin.com/qVtRMCYc

this is the error that occurs when I turn on /znpcs glow without specifying the glow color. (the NPC disappears and everything breaks)
However, even if I specify it, no glow appears in the NPC

(otherwise nothing new)

**Comment by Pyrbu** [comment]
This is an issue with the scuffed command system and is practically unfixable with the current state of the code because of how messy it is, this will most likely be an issue for a long time before me or someone else gets around to rewriting the NPC property system.

**Comment by Overwrite987** [comment]
> This is an issue with the scuffed command system and is practically unfixable with the current state of the code because of how messy it is, this will most likely be an issue for a long time before me or someone else gets around to rewriting the NPC property system.
![fade-away-oooooooooooo](https://user-images.githubusercontent.com/92237090/233804441-5d197458-38d7-486f-961e-f9b96e20d953.gif)

**Comment by Pyrbu** [comment]
Glow has been fixed in the entity rewrite
