### ISSUE TITLE
Unable to build with Jitpack

### ISSUE THREAD

**Issue by PikaMug** [Pyrbu/ZNPCsPlus#21]
See log https://www.jitpack.io/com/github/Pyrbu/ZNPCsPlus/1.0.5/build.log

**Comment by Pyrbu** [comment]
Are you trying to use the plugin as a library? I can publish it to my own repository if you would like.

**Comment by Pyrbu** [comment]
Please use the following, I will probably extract an API out of the project soon and add it to the readme so keep an eye out for that
`
maven {
    url "https://repo.pyr.lol/releases"
}
compileOnly "lol.pyr:ZNPCsPlus:1.0.5"
`
