### ISSUE TITLE
Support to Folia

### ISSUE THREAD

**Issue by Aitooor** [Pyrbu/ZNPCsPlus#24]
It will possible to add Folia support?

Folia url: https://github.com/PaperMC/Folia

**Comment by Pyrbu** [comment]
It's definitely possible but I would need to do a bit of research to figure out what is needed to support it.

**Comment by Aitooor** [comment]
> It's definitely possible but I would need to do a bit of research to figure out what is needed to support it.

Thanks 👍

**Comment by PikaMug** [comment]
I can't get Folia to compile locally. If there's a jar floating around, I'd be willing to try it out.

**Comment by Pyrbu** [comment]
> I can't get Folia to compile locally. If there's a jar floating around, I'd be willing to try it out.

Are you by any chance using Windows?

**Comment by Aitooor** [comment]
> It's definitely possible but I would need to do a bit of research to figure out what is needed to support it.

Do you have any news?

**Comment by PikaMug** [comment]
> Do you have any news?

📰 Sharp economic slowdown triggers new recession fears

Adding support for a new platform is not a simple task (if they choose to). Please have patience.

**Comment by Pyrbu** [comment]
Support for folia has been added

**Comment by Aitooor** [comment]
> Support for folia has been added

Where is it? I don't find it

**Comment by Pyrbu** [comment]
> > Support for folia has been added
> 
> Where is it? I don't find it

It is in the entity rewrite branch, it will probably be released soon as version 2.0 due to the amount of code that has changed

**Comment by Aitooor** [comment]
> > > Support for folia has been added
> 
> > 
> 
> > Where is it? I don't find it
> 
> 
> 
> It is in the entity rewrite branch, it will probably be released soon as version 2.0 due to the amount of code that has changed

Thanks for your support. And for your time too
