### ISSUE TITLE
Dependency Hook

### ISSUE THREAD

**Issue by AjMaacc** [Pyrbu/ZNPCsPlus#26]
I was wondering if there was a new dependency that I can hook into for one of my plugins.
Thought it would be in the form of
```
        <dependency>
            <groupId>lol.pyr.ZNPCsPlus</groupId>
            <artifactId>ZNPCsPlus</artifactId>
            <version>1.0.5</version>
            <scope>provided</scope>
        </dependency>
```

But this doesn't work. The previous one I had for the old plugin was

```
        <dependency>
            <groupId>io.github.znetworkw.znpcservers</groupId>
            <artifactId>znpcservers</artifactId>
            <version>3.6</version>
        </dependency>
```

**Comment by AjMaacc** [comment]
Tried this from your maven repo
```
        <dependency>
            <groupId>lol.pyr</groupId>
            <artifactId>ZNPCsPlus</artifactId>
            <version>1.0.5</version>
        </dependency>
```
Still doesn't work

**Comment by Pyrbu** [comment]
> Tried this from your maven repo
> 
> ```
>         <dependency>
>             <groupId>lol.pyr</groupId>
>             <artifactId>ZNPCsPlus</artifactId>
>             <version>1.0.5</version>
>         </dependency>
> ```
> 
> Still doesn't work

You probably forgot to add the repository
```
<repository>
  <id>pyr</id>
  <url>https://repo.pyr.lol/<repository></url>
</repository>
```

**Comment by AjMaacc** [comment]
> **For Maven -**
> 
> ```
> <repository>
> 	<id>lol.pyr</id>
> 	<name>Pyr's Repo</name>
> 	<url>https://repo.pyr.lol/releases/</url>
> </repository>
> <repository>
> 	<id>jitpack.io</id>
> 	<url>https://jitpack.io</url>
> </repository>
> <repository>
> 	<id>codemc-snapshots</id>
> 	<url>https://repo.codemc.io/repository/maven-snapshots/</url>
> </repository>
> ```
> 
> ```
> <dependency>
> 	<groupId>lol.pyr</groupId>
> 	<artifactId>ZNPCsPlus</artifactId>
> 	<version>1.0.5</version>
> </dependency>
> ```

Works perfectly, thank you!
