### ISSUE TITLE
Plugin issue

### ISSUE THREAD

**Issue by MatinHQ** [Pyrbu/ZNPCsPlus#28]
Hello I am using Purpur 1.19.4 and I migrated from ZNpc to this ZNPCsPlus but the problem is all of my NPC names changed to armor stand also some of them get invisible often and get visible again also there was a error when the plugin tries to start up
![image](https://user-images.githubusercontent.com/22664859/234355209-fd489b59-5225-4c5a-82e7-857ead3c294b.png)
![image](https://user-images.githubusercontent.com/22664859/234355268-28d311b2-2dcf-4da3-bf34-73610681c477.png)
![image](https://user-images.githubusercontent.com/22664859/234355338-e4d11620-3af3-4c9e-9528-02b7a5e3ee94.png)

Error:
```[17:23:34 WARN]: [ZNPCsPlus] Plugin ZNPCsPlus v1.0.5 generated an exception while executing task 59
survival  | java.lang.NullPointerException: Cannot invoke "lol.pyr.znpcsplus.lib.spigotresources.api.Resource.getVersion()" because "resource" is null
survival  |     at lol.pyr.znpcsplus.updater.UpdateChecker.run(UpdateChecker.java:26) ~[ZNPCsPlus-1.0.5.jar:?]
survival  |     at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.4.jar:git-Purpur-1962]
survival  |     at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.4.jar:git-Purpur-1962]
survival  |     at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.4.jar:?]
survival  |     at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
survival  |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
survival  |     at java.lang.Thread.run(Unknown Source) ~[?:?]
```

**Comment by Pyrbu** [comment]
What ZNPCs version were you using before?

**Comment by MatinHQ** [comment]
I was using version 3.9 and sure I will attach the full plugin data folder
[ZNPCsPlus.zip](https://github.com/Pyrbu/ZNPCsPlus/files/11336478/ZNPCsPlus.zip)

**Comment by Pyrbu** [comment]
It doesn't look like there's anything wrong with the data and it works perfectly good for me on Purpur 1.19.4.
![image](https://user-images.githubusercontent.com/75636092/234685081-9118762e-0597-4f52-ad2b-bc33e73a8e08.png)
This must be an issue with another plugin, if you send me a list of your plugins I might be able to tell you which one.

**Comment by MatinHQ** [comment]
Can you please accept my friend request at Discord, I will send you there Matin#2511
