### ISSUE TITLE
Maintained with ?

### ISSUE THREAD

**Issue by PikaMug** [Pyrbu/ZNPCsPlus#30]
Figure it's supposed to be a heart in Unicode? Maybe just use `<3` instead.

![splash](https://user-images.githubusercontent.com/2267126/234448836-c8f49a00-3687-42e4-ada1-cc9a8c07394c.png)

**Comment by Pyrbu** [comment]
In most modern consoles like Pterodactyl it shows up correctly and looks much better than a `<3`
![image](https://user-images.githubusercontent.com/75636092/234454343-a3e75da4-10da-4350-b1cf-5f1f295271a1.png)

**Comment by Pyrbu** [comment]
Maybe if you could figure out some way of determining if a specific console supports the Unicode and switching it out dynamically we could do that but I don't think it's worth all that effort.
