### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by daniel-skopek** [Pyrbu/ZNPCsPlus#31]
I'm getting this error on my first server:
`[19:02:40 WARN]: [ZNPCsPlus] Plugin ZNPCsPlus v1.0.5 generated an exception while executing task 8960`
`java.lang.NullPointerException: null `

All NPCs have disappeared and are not visible.

-------

Second server: Only some NPCs are visible.
Error: https://pastebin.com/raw/NG7tdtU9

-------

ZNPCsPlus version: 1.0.5
Server: Pufferfish-61 (1.19.3)

**Comment by Pyrbu** [comment]
This was already fixed in cf34ddc32eec0a4e2f022c2c72bbc635997721c2
