### ISSUE TITLE
Java 8 Support

### ISSUE THREAD

**Issue by PikaMug** [Pyrbu/ZNPCsPlus#33]
While I support encouraging end users to use the latest version of Java, I'm curious if there is an actual need for ZNPCsPlus to compile with it, given it supports older Minecraft versions?

Requiring Java 17 prevents Java 8 resources which depend on ZNPCsPlus from doing so properly ([example](https://ci.codemc.io/job/PikaMug/job/Quests/408/me.blackvein.quests$quests-api/console)). There are "valid" reasons for server owners to run it, such as running [HyperConomy](https://dev.bukkit.org/projects/hyperconomy) on older servers, which Java 9 broke due to major reflection changes. It's also not a matter of security - Java 8 continues to receive updates as recently as [this month](https://www.java.com/en/download/java8_update.jsp).

So if there's no technical reason for compiling against Java 17, would you consider Java 8? I could fork & pull request.

**Comment by Pyrbu** [comment]
The only reason for using modern java is the newer language versions such as (enhanced instanceof)[https://www.baeldung.com/java-pattern-matching-instanceof] but I am willing to sacrifice those to add Java 8 support. If you want to you can create a PR or you can wait for me to get to doing it but it might take a couple days.

**Comment by PikaMug** [comment]
The newer features are nice, but worth sacrificing compatibility imho. Glad to take of it, I'm sure you have enough on your plate.

**Comment by PikaMug** [comment]
You're too fast! Many thanks.
