### ISSUE TITLE
Occasionally some NPCs disappear

### ISSUE THREAD

**Issue by daniel-skopek** [Pyrbu/ZNPCsPlus#35]
It happens that occasionally some NPCs disappear. I don't think it shows any error.

ZNPCsPlus version: 1.0.5
Server: Pufferfish-59 (MC: 1.19.3)

**Comment by Overwrite987** [comment]
> It happens that occasionally some NPCs disappear. I don't think it shows any error.
> 
> ZNPCsPlus version: 1.0.5 Server: Pufferfish-59 (MC: 1.19.3)

I thought it was a visual bug, but damn it, it turned out I'm not the only one with such a problem...
but i'm using 1.19.4 (Plazma)

**Comment by Pyrbu** [comment]
This is a known issue and should be fixed in the 2.0.0 branch, I will keep this issue open as a reminder and so people stop reporting the same thing.
