### ISSUE TITLE
CRITICAL BUG: IndexOutOfBoundsException

### ISSUE THREAD

**Issue by daniel-skopek** [Pyrbu/ZNPCsPlus#36]
If I teleport to NPCs while sing vanilla Minecraft 1.19.3, the server kicks me out with this error message: https://i.imgur.com/5r3Qdvg.png

With Minecraft 1.19.4 it's working without any problem.

Server version: Pufferfish-59 (MC: 1.19.3)
ZNPCsPlus version: 1.0.5 (**Built from GitHub on April 30**)

**Comment by Pyrbu** [comment]
Can you please test with that commit that was just mentioned? If it really was the fix to issue #25 then it will be fixed by that commit
