### ISSUE TITLE
java.lang.ClassNotFoundException: No class found

### ISSUE THREAD

**Issue by Brasil150** [Pyrbu/ZNPCsPlus#5]
Hi, the idea is great! The original has many problems even. But I want to say that this fork is creating infinite Exceptions on my server. Where could I get support?

https://mclo.gs/5ldvBPd
And then, even off, I get the following infinite log:
https://mclo.gs/CrbFQtE

Server version: Flamepaper - 1.8.8
Java version: openjdk 17.0.6 2023-01-17
O.S.: Windows 7 x64

**Comment by JosTheDude** [comment]
Huh, looks like entities from modern versions are being loaded into the cache for some reason

**Comment by Pyrbu** [comment]
Actual issue fixed in latest release, cache warning spam will be fixed soon.
