### ISSUE TITLE
[Folia] Dispatch Command error

### ISSUE THREAD

**Issue by Aitooor** [Pyrbu/ZNPCsPlus#54]
Branch: 2.0.0
Commit used: https://github.com/Pyrbu/ZNPCsPlus/commit/5ae5ca200d3a01d2d0261a0b3b975d19305230c8

Error lines: https://paste.md-5.net/awuvequqiv.bash

You need to use Global Region for dispatch commands in Folia `Server#dispatchCommand` 

Example:
```java
plugin.getServer().getGlobalRegionScheduler().run(plugin, scheduledTask ->
    plugin.getServer().dispatchCommand(plugin.getServer().getConsoleSender(), command)
);
```

**Comment by D3v1s0m** [comment]
@Aitooor , is that the correct commit ?

**Comment by Pyrbu** [comment]
We are already doing, console commands work perfectly fine the issue is with player commands. I have no clue which scheduler to use for those, any ideas?

**Comment by Aitooor** [comment]
Sorry, I was out of my house.
