### ISSUE TITLE
Action order inconsistent

### ISSUE THREAD

**Issue by D3v1s0m** [Pyrbu/ZNPCsPlus#56]
The order of the actions being executed is incorrect. Although the second action is a player command action, it should still execute before the third one, or the third action should somehow wait for the second action to be completed.

Also, adding a delay that can be set such that the next action runs after that many ticks would be better option to fix this issue.

![image](https://github.com/Pyrbu/ZNPCsPlus/assets/49519439/21ae1e9c-c01c-49c0-8ab5-ef14b7ea9317)

**Comment by Pyrbu** [comment]
Adding a delay isnt the right solution for this issue, we should instead just add an "index" variable to the actions and sort the action list by it

**Comment by Pyrbu** [comment]
This would be too impractical to fix this since command actions need to be scheduled to be ran on the main server thread while the others don't so this is a won't fix
