### ISSUE TITLE
Cannot invoke "java.util.UUID.getMostSignificantBits()" because "uuid" is null

### ISSUE THREAD

**Issue by kforbro** [Pyrbu/ZNPCsPlus#59]
https://yaso.su/p6ncaE0V

I tried to unload the TAB plugin using PluginManager, but it didn't help. 

Purpur 1.19.4, ZNPCsPlus 1.0,8

**Comment by D3v1s0m** [comment]
> https://yaso.su/p6ncaE0V
> 
> I tried to unload the TAB plugin using PluginManager, but it didn't help.
> 
> Purpur 1.19.4, ZNPCsPlus 1.0,8

As Purpur is not officially supported, can you please try the same on a spigot or paper server?

**Comment by Pyrbu** [comment]
> https://yaso.su/p6ncaE0V
> 
> I tried to unload the TAB plugin using PluginManager, but it didn't help.
> 
> Purpur 1.19.4, ZNPCsPlus 1.0,8

Is this the only error that is happening? There should be a lot more errors if the uuid of the player's GameProfile is null

**Comment by kforbro** [comment]
Not fixed

**Comment by kforbro** [comment]
There is no such error with ZNPCsPlus 1.0.7
