### ISSUE TITLE
I cant add " - " to my npcs

### ISSUE THREAD

**Issue by rw4207** [Pyrbu/ZNPCsPlus#62]
symbol - doesn't work, it is treated as whitespace

**Comment by D3v1s0m** [comment]
> symbol - doesn't work, it is treated as whitespace

@RWONG722 , you can change REPLACE_SYMBOL in config.json to something else instead of '-'.
Note: please ask on the support discord before creating an issue on github. https://discord.gg/e9f49nay

**Comment by RWONG722** [comment]
> symbol - doesn't work, it is treated as whitespace
