### ISSUE TITLE
/znpcs near Exception if entity in another world

### ISSUE THREAD

**Issue by EternalHuman** [Pyrbu/ZNPCsPlus#69]
/znpcs near Exception (distance between different worlds) if entity in another world.

**Comment by D3v1s0m** [comment]
> /znpcs near Exception (distance between different worlds) if entity in another world.

can you attach a photo of this error?

**Comment by EternalHuman** [comment]
> > /znpcs near Exception (distance between different worlds) if entity in another world.
> 
> can you attach a photo of this error?

![image](https://github.com/Pyrbu/ZNPCsPlus/assets/71584363/68549bc0-b4b8-437e-9378-bded5f03281e)
