### ISSUE TITLE
memory leak (build #102)

### ISSUE THREAD

**Issue by Teslicek** [Pyrbu/ZNPCsPlus#84]
Self-explanatory.

![image](https://github.com/Pyrbu/ZNPCsPlus/assets/87967222/73485326-5d3a-4835-ade8-f831a24bc47c)
Image taken after 11h uptime. (Have at least 3 more heap dumps with the same high memory usage between different restarts.)

(dont mind ajleaderboards, working on that one)

Discord: txslx (in case you need full image etc)

**Comment by Teslicek** [comment]
![image](https://github.com/Pyrbu/ZNPCsPlus/assets/87967222/481265e8-3279-4be4-833c-1830302c6923)

This is another heap dump after 24h uptime. Looks much better, so it's probably not a memory leak, just a pretty big memory usage compared to other plugins (such as decentholograms, etc).

It's probably nothing serious, but just thought I'd be good to point out in case someone else also noticed it.

**Comment by Pyrbu** [comment]
Could you please upload the heap dump file to a file sharing service and send me the link on discord (@pyrbu) so I can take a look?

**Comment by Pyrbu** [comment]
Fixed in f1c59d0
