### ISSUE TITLE
#103: Cannot click through holograms

### ISSUE THREAD

**Issue by Teslicek** [Pyrbu/ZNPCsPlus#85]
Self-explanatory.

https://www.youtube.com/watch?v=4rWfcDRdlWU

**Comment by Pyrbu** [comment]
I believe I fixed this a long time ago, can you please tell me what build you're using? Also this is a small issue because it only happens in creative mode since you cant click invisible entities when not in creative on modern versions.

**Comment by Teslicek** [comment]
Unfortunately, it happens even in survival. I was using build #103.

**Comment by Pyrbu** [comment]
This needs to be re-tested now since the branches have been merged and I believe the commit that fixed this was in one of them.

**Comment by Pyrbu** [comment]
This seems to be fixed.
