### ISSUE TITLE
Hologram Memory Leak

### ISSUE THREAD

**Issue by R00tB33rMan** [Pyrbu/ZNPCsPlus#87]
Internal holograms appear to have a severe memory leak, as indicated in this report:
![image](https://github.com/Pyrbu/ZNPCsPlus/assets/36140389/102a26cb-9e1a-4aa0-8d13-f3e238482b43)

**Comment by Pyrbu** [comment]
Is this on the latest dev build? If no, I'm pretty sure this is a duplicate of #84

**Comment by R00tB33rMan** [comment]
> Is this on the latest dev build? If no, I'm pretty sure this is a duplicate of #84

It is, yes. Build 107. Very obscure issue for sure. I’ll confirm with the client and see if this has been properly upgraded; however, I believe it has

**Comment by Pyrbu** [comment]
Fixed by 868999fe2d6aead1567d455e1e1fec801e1ae311
