### ISSUE TITLE
Allow non-registered commands to be executed

### ISSUE THREAD

**Issue by SladeHazard** [Pyrbu/ZNPCsPlus#95]
Whenever I give the npc a command such as /warp created by plugins such as DeluxeMenus, which aren't registered commands the plugin does not work with them

![image](https://github.com/Pyrbu/ZNPCsPlus/assets/45261094/8f63cfd4-6dbd-4128-9219-bd98b214af05)

Whenever I click the NPC it says unknown command even though the command exists, it's just not registered... this does not happen with the Citizens plugin. and you might say: "why not just register the command?" in some use cases registering the command isn't possible for example if I register the command /plot for my deluxemenu gui it'll completely make my plotsquared plugin disfunctional when executing other commands such as /plot teleport

**Comment by D3v1s0m** [comment]
> Whenever I give the npc a command such as /warp created by plugins such as DeluxeMenus, which aren't registered commands the plugin does not work with them
> 
> ![image](https://user-images.githubusercontent.com/45261094/275251485-8f63cfd4-6dbd-4128-9219-bd98b214af05.png)
> 
> Whenever I click the NPC it says unknown command even though the command exists, it's just not registered... this does not happen with the Citizens plugin. and you might say: "why not just register the command?" in some use cases registering the command isn't possible for example if I register the command /plot for my deluxemenu gui it'll completely make my plotsquared plugin disfunctional when executing other commands such as /plot teleport

you either need to [register the command](https://wiki.helpch.at/clips-plugins/deluxemenus/options-and-configurations/gui#register-command) using that plugin or you need to use the chat action type for 1.0.8 or playerchat action type for 2.0.0 snapshots.
example:
`/znpcs action add 1 CHAT /warp pvp` for 1.0.8
`/npc action add playerchat 1 ANY_CLICK 1 0 /warp pvp` for 2.0.0 snapshots

**Comment by SladeHazard** [comment]
Thank you that solved it!
